//! "Export workers as an application" — bundles a selection of the console's
//! embedded workers into a **standalone, runnable Deno application**, downloaded
//! as a single `.zip` the user can run and manage themselves.
//!
//! The generated app is self-contained:
//!
//! ```text
//! nano-workers-app/
//!   README.md              how to run it
//!   deno.json              import map + `start` task (network + file permissions)
//!   main.ts                entrypoint: deploy resources/*.bpmn, then run the workers
//!   sdk/worker-sdk.ts      the embedded Nano worker SDK (verbatim)
//!   workers/<name>/…       one folder per selected worker (worker.ts + helpers)
//!   resources/             the user drops their .bpmn models here (deployed on startup)
//! ```
//!
//! On startup `main.ts` deploys every `.bpmn` in `resources/` to the gateway
//! (`POST /v2/deployments`, idempotent) and then starts each bundled worker,
//! which connects to the gateway's command stream and processes its job type.
//!
//! The archive is written by a tiny self-contained **STORED** (uncompressed) zip
//! builder so the server needs no zip crate — the bundled files are small text.

use super::workspace;

/// The worker SDK source, baked into the binary (the same file the supervisor
/// materialises to disk). Shipped verbatim into the exported app's `sdk/` so it
/// stays a single source of truth with the running server.
const WORKER_SDK_TS: &str = include_str!("worker_sdk.ts");

/// Top-level folder the zip extracts into (so unzipping never splats into cwd).
const APP_ROOT: &str = "nano-workers-app";

/// Build the standalone-application zip for the given worker names. Returns the
/// zip bytes, or an error string (bad/empty selection, unreadable worker).
pub fn build_app(worker_names: &[String]) -> Result<Vec<u8>, String> {
    if worker_names.is_empty() {
        return Err("select at least one worker to export".into());
    }

    let mut entries: Vec<(String, Vec<u8>)> = Vec::new();
    let at = |path: &str| format!("{APP_ROOT}/{path}");

    // Validate + collect each worker's source files (skip its deno.json — the app
    // uses a single root import map instead).
    let mut valid_names: Vec<String> = Vec::new();
    for name in worker_names {
        let Some(dir) = workspace::worker_dir(name) else {
            return Err(format!("invalid worker name: {name}"));
        };
        if !dir.is_dir() {
            return Err(format!("no such worker: {name}"));
        }
        let files = workspace::list_worker_files(name)
            .map_err(|e| format!("could not read worker '{name}': {e}"))?;
        let mut copied_entrypoint = false;
        for file in files {
            if file == "deno.json" {
                continue;
            }
            let Some(path) = workspace::worker_file_path(name, &file) else {
                continue;
            };
            let bytes = std::fs::read(&path)
                .map_err(|e| format!("could not read {name}/{file}: {e}"))?;
            if file == "worker.ts" {
                copied_entrypoint = true;
            }
            entries.push((at(&format!("workers/{name}/{file}")), bytes));
        }
        if !copied_entrypoint {
            return Err(format!("worker '{name}' has no worker.ts entrypoint"));
        }
        valid_names.push(name.clone());
    }

    // Generated app scaffolding.
    entries.push((at("sdk/worker-sdk.ts"), WORKER_SDK_TS.as_bytes().to_vec()));
    entries.push((at("deno.json"), DENO_JSON.as_bytes().to_vec()));
    entries.push((at("main.ts"), main_ts(&valid_names).into_bytes()));
    entries.push((at("README.md"), readme_md(&valid_names).into_bytes()));
    entries.push((
        at("resources/README.txt"),
        RESOURCES_README.as_bytes().to_vec(),
    ));

    // Stable order so the archive is deterministic.
    entries.sort_by(|a, b| a.0.cmp(&b.0));
    Ok(build_stored_zip(&entries))
}

/// Suggested download filename.
pub fn zip_filename() -> &'static str {
    "nano-workers-app.zip"
}

const DENO_JSON: &str = r#"{
  "imports": {
    "@nanobpm/worker": "./sdk/worker-sdk.ts"
  },
  "tasks": {
    "start": "deno run --allow-net --allow-read --allow-env main.ts"
  }
}
"#;

const RESOURCES_README: &str = "Drop the .bpmn model files your workers serve into this folder.\n\
Every .bpmn here is deployed to the gateway when the app starts (idempotently).\n";

/// The app entrypoint: deploy `resources/*.bpmn`, then start each worker.
fn main_ts(names: &[String]) -> String {
    let list = names
        .iter()
        .map(|n| format!("  {}", json_string(n)))
        .collect::<Vec<_>>()
        .join(",\n");
    format!(
        r#"// Standalone nano workers application — generated by the Nano Console.
//
// On startup it (1) deploys every BPMN model in ./resources to the gateway, then
// (2) starts each bundled worker, which connects to the gateway's command stream
// and processes its job type. Point it at your gateway with NANOBPMN_BASE_URL
// (default http://127.0.0.1:8080). Run it with `deno task start`.

const BASE_URL = (Deno.env.get("NANOBPMN_BASE_URL") ?? "http://127.0.0.1:8080").replace(/\/+$/, "");

// One folder under ./workers per worker bundled into this app.
const WORKERS: string[] = [
{list}
];

async function deployResources(): Promise<void> {{
  let dirEntries: Deno.DirEntry[];
  try {{
    dirEntries = [...Deno.readDirSync("resources")];
  }} catch {{
    console.log("[deploy] no ./resources directory — nothing to deploy");
    return;
  }}
  const models = dirEntries
    .filter((e) => e.isFile && e.name.toLowerCase().endsWith(".bpmn"))
    .map((e) => e.name)
    .sort();
  if (models.length === 0) {{
    console.log("[deploy] no .bpmn models in ./resources — add your models there and restart");
    return;
  }}
  for (const name of models) {{
    try {{
      const xml = await Deno.readTextFile(`resources/${{name}}`);
      const form = new FormData();
      form.append("resources", new Blob([xml], {{ type: "text/xml" }}), name);
      const res = await fetch(`${{BASE_URL}}/v2/deployments`, {{ method: "POST", body: form }});
      if (res.ok) {{
        console.log(`[deploy] ${{name}} ok`);
      }} else {{
        const detail = await res.text().catch(() => "");
        console.error(`[deploy] ${{name}} failed: HTTP ${{res.status}} ${{detail}}`);
      }}
    }} catch (err) {{
      console.error(`[deploy] ${{name}} failed: ${{err instanceof Error ? err.message : err}}`);
    }}
  }}
}}

async function startWorkers(): Promise<void> {{
  for (const name of WORKERS) {{
    try {{
      // Label this worker's command-stream activations with its folder name.
      Deno.env.set("NANOBPMN_WORKER_NAME", name);
      await import(`./workers/${{name}}/worker.ts`);
      console.log(`[worker] ${{name}} started`);
    }} catch (err) {{
      console.error(`[worker] ${{name}} failed to start: ${{err instanceof Error ? err.message : err}}`);
    }}
  }}
}}

console.log(`nano workers app -> gateway ${{BASE_URL}}`);
await deployResources();
await startWorkers();
console.log(`${{WORKERS.length}} worker(s) running. Press Ctrl+C to stop.`);
"#
    )
}

/// The exported app's README.
fn readme_md(names: &[String]) -> String {
    let worker_list = names
        .iter()
        .map(|n| format!("- `{n}`"))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        r#"# Nano workers application

A standalone bundle of job workers exported from the **Nano Console**. It connects
to a running **Nano BPM** gateway, deploys your BPMN models, and runs the workers —
no Console required.

## Prerequisites

- **[Deno](https://deno.com)** — the runtime the workers run on (`curl -fsSL https://deno.land/install.sh | sh`).
- A running **Nano BPM** gateway (default `http://127.0.0.1:8080`).

## 1. Add your models

Drop the `.bpmn` files your workers serve into the **`resources/`** folder. Every
model there is deployed to the gateway on startup (deployment is idempotent, so
restarting safely re-deploys).

## 2. Point at your gateway (optional)

Defaults to `http://127.0.0.1:8080`. Override with an environment variable:

```sh
export NANOBPMN_BASE_URL=http://my-gateway:8080
```

## 3. Run

```sh
deno task start
```

(equivalently: `deno run --allow-net --allow-read --allow-env main.ts`)

The app deploys `resources/*.bpmn`, then starts these workers:

{worker_list}

Each worker connects to the gateway's command stream and processes its job type.
Workers print periodic telemetry lines (prefixed `@@NBPM_`, used by the Console)
alongside their own `console.log` output. Press **Ctrl+C** to stop.

## Layout

```text
main.ts              entrypoint (deploy models, then run workers)
deno.json            import map + `start` task (network + file permissions)
sdk/worker-sdk.ts    the embedded Nano worker SDK
workers/<name>/      one folder per worker (worker.ts + any helpers)
resources/           drop your .bpmn models here
```

## Editing workers

Each `workers/<name>/worker.ts` imports `@nanobpm/worker` and calls `defineWorker`.
Edit the handler, add `npm:`/`jsr:` dependencies as needed, and re-run.
"#
    )
}

// ---------------------------------------------------------------------------
// Minimal STORED (uncompressed) zip writer — no external zip crate needed.
// ---------------------------------------------------------------------------

/// Build a zip archive from `(path, bytes)` entries using STORED (no
/// compression). The bundled files are small text, so compression buys little
/// and a dependency-free writer keeps the gateway lean.
fn build_stored_zip(entries: &[(String, Vec<u8>)]) -> Vec<u8> {
    // Fixed DOS timestamp (1980-01-01 00:00) — valid and deterministic.
    const DOS_DATE: u16 = 0x0021;
    const DOS_TIME: u16 = 0x0000;
    // General-purpose bit 11: filenames are UTF-8.
    const FLAG_UTF8: u16 = 0x0800;

    let mut out: Vec<u8> = Vec::new();
    let mut central: Vec<u8> = Vec::new();

    for (name, data) in entries {
        let name_bytes = name.as_bytes();
        let crc = crc32fast::hash(data);
        let size = data.len() as u32;
        let offset = out.len() as u32;

        // Local file header.
        out.extend_from_slice(&0x0403_4b50u32.to_le_bytes());
        out.extend_from_slice(&20u16.to_le_bytes()); // version needed
        out.extend_from_slice(&FLAG_UTF8.to_le_bytes());
        out.extend_from_slice(&0u16.to_le_bytes()); // method: stored
        out.extend_from_slice(&DOS_TIME.to_le_bytes());
        out.extend_from_slice(&DOS_DATE.to_le_bytes());
        out.extend_from_slice(&crc.to_le_bytes());
        out.extend_from_slice(&size.to_le_bytes()); // compressed
        out.extend_from_slice(&size.to_le_bytes()); // uncompressed
        out.extend_from_slice(&(name_bytes.len() as u16).to_le_bytes());
        out.extend_from_slice(&0u16.to_le_bytes()); // extra len
        out.extend_from_slice(name_bytes);
        out.extend_from_slice(data);

        // Central directory record.
        central.extend_from_slice(&0x0201_4b50u32.to_le_bytes());
        central.extend_from_slice(&20u16.to_le_bytes()); // version made by
        central.extend_from_slice(&20u16.to_le_bytes()); // version needed
        central.extend_from_slice(&FLAG_UTF8.to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes()); // method
        central.extend_from_slice(&DOS_TIME.to_le_bytes());
        central.extend_from_slice(&DOS_DATE.to_le_bytes());
        central.extend_from_slice(&crc.to_le_bytes());
        central.extend_from_slice(&size.to_le_bytes());
        central.extend_from_slice(&size.to_le_bytes());
        central.extend_from_slice(&(name_bytes.len() as u16).to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes()); // extra len
        central.extend_from_slice(&0u16.to_le_bytes()); // comment len
        central.extend_from_slice(&0u16.to_le_bytes()); // disk number start
        central.extend_from_slice(&0u16.to_le_bytes()); // internal attrs
        central.extend_from_slice(&0u32.to_le_bytes()); // external attrs
        central.extend_from_slice(&offset.to_le_bytes());
        central.extend_from_slice(name_bytes);
    }

    let central_offset = out.len() as u32;
    let central_size = central.len() as u32;
    let count = entries.len() as u16;
    out.extend_from_slice(&central);

    // End of central directory.
    out.extend_from_slice(&0x0605_4b50u32.to_le_bytes());
    out.extend_from_slice(&0u16.to_le_bytes()); // disk number
    out.extend_from_slice(&0u16.to_le_bytes()); // disk with cd
    out.extend_from_slice(&count.to_le_bytes());
    out.extend_from_slice(&count.to_le_bytes());
    out.extend_from_slice(&central_size.to_le_bytes());
    out.extend_from_slice(&central_offset.to_le_bytes());
    out.extend_from_slice(&0u16.to_le_bytes()); // comment len
    out
}

/// JSON-encode a string (for embedding worker names in generated TS).
fn json_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_selection_is_rejected() {
        assert!(build_app(&[]).is_err());
    }

    #[test]
    fn json_string_escapes() {
        assert_eq!(json_string("a-b_1"), "\"a-b_1\"");
        assert_eq!(json_string("a\"b\\c"), "\"a\\\"b\\\\c\"");
    }

    #[test]
    fn main_ts_lists_workers_and_deploys() {
        let ts = main_ts(&["alpha".into(), "beta".into()]);
        assert!(ts.contains("\"alpha\""));
        assert!(ts.contains("\"beta\""));
        assert!(ts.contains("/v2/deployments"));
        assert!(ts.contains("./workers/${name}/worker.ts"));
    }

    #[test]
    fn stored_zip_has_valid_signatures_and_eocd() {
        let entries = vec![
            ("nano-workers-app/main.ts".to_string(), b"hello".to_vec()),
            ("nano-workers-app/README.md".to_string(), b"# hi".to_vec()),
        ];
        let zip = build_stored_zip(&entries);
        // Local file header signature at the very start.
        assert_eq!(&zip[0..4], &0x0403_4b50u32.to_le_bytes());
        // End-of-central-directory signature appears near the end.
        let eocd = &0x0605_4b50u32.to_le_bytes();
        assert!(
            zip.windows(4).any(|w| w == eocd),
            "EOCD signature must be present"
        );
        // Entry count in EOCD (last 22 bytes) must be 2.
        let tail = &zip[zip.len() - 22..];
        let count = u16::from_le_bytes([tail[10], tail[11]]);
        assert_eq!(count, 2);
    }
}
