// AUTO-GENERATED credits roster. Source: git contributor history across
// camunda/camunda, camunda/zeebe, camunda/camunda-bpm-platform, camunda/feel-scala,
// bpmn-io/{bpmn-js,diagram-js,bpmn-moddle,dmn-js,form-js}, camunda/camunda-modeler.
// Deduped by display name; bots removed. Regenerate rather than hand-edit.

export interface CreditLine { name: string; area?: string; subsystem?: string; role?: string }

export const credits = {
  "producer": {
    "name": "Joshua Wulf",
    "role": "Nano Producer"
  },
  "signed": [
    {
      "subsystem": "Falcon Protocol",
      "area": "Command-stream protocol",
      "name": "Falko Menge"
    },
    {
      "subsystem": "Deepthi",
      "area": "Single-writer engine actor",
      "name": "Deepthi Devaki Akkoorath"
    },
    {
      "subsystem": "FEEL",
      "area": "Expression language",
      "name": "Philipp Ossler"
    },
    {
      "subsystem": "DMN (reserved)",
      "area": "Decision engine",
      "name": "Sebastian Menski"
    }
  ],
  "founders": [
    {
      "name": "Daniel Meyer",
      "area": "Camunda · Zeebe origin"
    },
    {
      "name": "Thorben Lindhauer",
      "area": "Camunda · Zeebe origin"
    },
    {
      "name": "Nico Rehwaldt",
      "area": "bpmn-io · modeling toolkit"
    }
  ],
  "principals": [
    {
      "name": "Christopher Kujawa (Zell)",
      "area": "Stream processor · storage · logstreams · performance & monitoring"
    },
    {
      "name": "Nicolas Pepin-Perreault",
      "area": "Actor scheduler · exporters · performance"
    },
    {
      "name": "Lena Schönburg",
      "area": "Raft replication · journal"
    },
    {
      "name": "Deepthi Devaki Akkoorath",
      "area": "Distributed log · Raft · snapshots · actor scheduler"
    },
    {
      "name": "Remco Westerhoud",
      "area": "Process engine"
    },
    {
      "name": "Nico Korthout",
      "area": "Process engine · DMN"
    },
    {
      "name": "Philipp Ossler",
      "area": "FEEL expression language"
    },
    {
      "name": "Sebastian Menski",
      "area": "Broker · transport · DMN"
    }
  ],
  "modeling": [
    {
      "name": "Nico Rehwaldt",
      "area": "bpmn-js · diagram-js"
    },
    {
      "name": "Philipp Fromme",
      "area": "Modeling toolkit"
    },
    {
      "name": "Maciej Barełkowski",
      "area": "Modeling toolkit"
    }
  ],
  "cast": [
    "Abbas Adel Ibraim",
    "Abdul Ahad",
    "Abdul Rehaman",
    "actions-user",
    "Adam Brengesjö",
    "adamscybot",
    "Adrián Marín",
    "Agustino Lim",
    "Ahmed AbouZaid",
    "Akif Hazarvi",
    "Akshita Singh",
    "Aleksander Dytko",
    "Aleksey Manetov",
    "Alexander Avdeev",
    "Alexander Skrock",
    "Alexander Tumin",
    "Alexandre",
    "Alexandre Bremard",
    "Alexey Vinogradov",
    "Alexis Zeghers",
    "Ali BARIN",
    "Aman Yadav",
    "Amar Deep Singh",
    "Ambrose Tan",
    "Amin Mohammed-Coleman",
    "Ana",
    "Ancoron Luciferis",
    "Andrea Giardini",
    "Andrea Rozaki",
    "Andreas Drobisch",
    "Andreas Geier",
    "Andreas Hauser",
    "Andreas Perhab",
    "Andrei Tropichev",
    "Andrey Marinchuk",
    "AndreyOS",
    "Andriy Chernysh",
    "Anna Pazola",
    "Anton von Weltzien",
    "Anupam Kumar",
    "aoraki",
    "Arezoo",
    "Arno Schutijzer",
    "Artem Gusev",
    "artem7992",
    "Ashish Maharjan",
    "asigner",
    "Askar Akhmerov",
    "atharwa_24",
    "aumaOne",
    "Balázs",
    "Barnabas Bodnar",
    "Bas Claessen",
    "Beatriz Mendes",
    "Ben Sheppard",
    "Benjamin Herbert",
    "Benjamin Hoffmann",
    "Benjamin Thurm",
    "berkaycanbc",
    "Bernd Ruecker",
    "Bingo-Soft",
    "Bojan Mudric",
    "Bojan Trajkovski",
    "Boris Petrov",
    "Bragolgirith",
    "Brian Varley",
    "Cameron Brown",
    "camundait",
    "capacia",
    "Carlo",
    "Carsten Wickner",
    "Catherina Prokudina",
    "Chaima Mansouri",
    "Chaitanya Babar",
    "Chaomin Ruan",
    "chaptergy",
    "Chris Lui",
    "Christian",
    "Christian Broomfield",
    "Christian Kaps",
    "Christian Konrad",
    "Christian Nicolai",
    "Christian Thiel",
    "Christina Ausley",
    "Christoph Fricke",
    "ChristopheDame",
    "Christopher Kujawa (Zell)",
    "Christopher Thomsen",
    "cigdemilhan",
    "Claude",
    "Claude Gex",
    "Clifton Davies",
    "Clément Nero",
    "Cody Gulley",
    "Corrado",
    "D3ns0n",
    "Daniel",
    "Daniel Kelemen",
    "Daniel Meyer",
    "Daniel Rodriguez",
    "Daniel Shuy",
    "Daniil",
    "Danilo Akamine",
    "Danny Gräf",
    "Dario Campagna",
    "Dave Paroulek",
    "Davey Chu",
    "David Benes",
    "David Castillo",
    "David de Lucca",
    "David Hodges",
    "david2202",
    "Davide Pastore",
    "Deepthi Devaki Akkoorath",
    "Deivarayan Azhagappan",
    "Dejan Ćebetarević",
    "dfulgham",
    "Dimitri Lavrenük",
    "Dimitrios Michail",
    "Dmitri Nikonov",
    "Dmitry",
    "Dmitry Molotchko",
    "dmytrivv2",
    "Dmytro Danylov",
    "Dmytro Melnychuk",
    "Dominik Broj",
    "Douglas Bouttell",
    "Dwiresti Puspita Rahmi",
    "Eamonn Moloney",
    "Edoardo Patti",
    "emilyoram",
    "Emma",
    "Eric Lundberg",
    "Erik Wiegel",
    "esraagamal6",
    "Euro",
    "Ev",
    "Fabian",
    "Fabio Paini",
    "Falko Menge",
    "Felix Linker",
    "Felix Müller",
    "Filip Hrisafov",
    "Filipe Campos",
    "flok32",
    "fml2",
    "Francesco Esposito",
    "Frank Langelage",
    "Franz Heidl",
    "Franz van Betteraey",
    "Fred",
    "Frederik Heremans",
    "GARCIA Guillaume",
    "Gareth Steyn",
    "Garima Yadav",
    "Gary Samuelson",
    "Gathin",
    "gbetances089",
    "GeethaParthasarathy",
    "George Gastaldi",
    "georgios-goulos",
    "Gergely Juhasz",
    "Giampaolo",
    "Giuliano Rodrigues Lima",
    "GmGamez",
    "Gonzalo Barco",
    "Gunnar von der Beck",
    "Gustavo Jiménez",
    "Hannes Brunner",
    "HarishMalavade",
    "hawky-4s-",
    "Helene",
    "Henry Yan",
    "Hilal",
    "Hilmi Erdem KEREN",
    "Hiren Pandit",
    "Hiroshi Ito",
    "hisImminence",
    "hkupitz",
    "Houssain Barouni",
    "HuangLiang",
    "Hüsna Uygur",
    "Igor N. Dultsev",
    "Igor Petrov",
    "Imgbot",
    "Ingo Richtsmeier",
    "Iurii Rybakov",
    "J4CKVVH173",
    "Jacek Poreda",
    "Jan Cheng",
    "Jan Friedenstab",
    "Jan Galinski",
    "Jan Ladleif",
    "Jan Rohwer",
    "Janik Schumacher",
    "Jarek Danielak",
    "jarrad78",
    "jcmaxsec",
    "Jeffrey Barrus",
    "Jens-Hilmar Bradt",
    "jeromew",
    "Jesse Simpson",
    "Jesse van Muijden",
    "Jia Huang",
    "jlaacke",
    "Joaquín",
    "Jochen Ulrich",
    "Joel Knott",
    "Joern",
    "Johannes Dollinger",
    "johanwelgemoed",
    "John Bampton",
    "John Montgomery",
    "JohnMTu",
    "jomo02",
    "Jonas Hecht",
    "Jonathan Ballet",
    "Jonathan Irwin",
    "Jonathan Leitschuh",
    "Jonathan Lukas",
    "Jonathan Roques",
    "Joram Barrez",
    "Jordy",
    "Josh Windels",
    "Josh Wulf",
    "Juja",
    "julioparrao",
    "jyotisahu9",
    "Jörg",
    "Jörn Horstmann",
    "Kane",
    "Karl San Gabriel",
    "KarpovIvan",
    "Kasper Aaquist Johansen",
    "Kenny",
    "kerem",
    "Kevin Fong",
    "KHADIR Tayeb",
    "kilida",
    "Klaus-Nji-sp",
    "Klaus-Peter Obst",
    "Konstantinos Mylosis",
    "Kostya Zraitel",
    "Kristin Komschow",
    "Kristin Polenz",
    "Kyrylo",
    "Lars Grefer",
    "Lars Lange",
    "Lars Uffmann",
    "Lena Schönburg",
    "Leonhardt Wille",
    "Lev Safro",
    "Libra",
    "Lilian",
    "lixiaofeng",
    "lo0",
    "logresearch",
    "Luc Weinbrecht",
    "Luca Arienti",
    "Luca Bonora",
    "Luca Cherubin",
    "Lucia",
    "Luiz Santana",
    "Lukas Taake",
    "László Pálossy",
    "m34434",
    "Maciej Barelkowski",
    "macoun",
    "Maksim Raspopov",
    "Marcos Barbero",
    "Marcos Vieira",
    "Marcus",
    "marfer",
    "Mariusz",
    "Mark Struberg",
    "Markus Hens",
    "Martin Mauch",
    "Martin Schimak",
    "Martin Stamm",
    "maryarm",
    "Mathias Geat",
    "Mathias Vandaele",
    "Mathieu Stennier",
    "Matt Bear",
    "Matt Van Horn",
    "matt-whiteman",
    "Matthew Kavanagh",
    "Matthias Bläsing",
    "Matthias Schmidt",
    "Matthijs Burke",
    "Mattia Buccarella",
    "Maxim Danilov",
    "Maxim Kalina",
    "MaxTru",
    "Mehdi Riahi",
    "Melissa Palmer",
    "Michael Scholz",
    "Michael Schöttes",
    "Michael W.",
    "Michaël Arnauts",
    "Michał Konopski",
    "Miguel Pires",
    "miiit",
    "Mike Winters",
    "Miklas Boskamp",
    "Miroslav Lehotsky",
    "MiyueFE",
    "mo-okocha",
    "Mohsen Hariri",
    "Mojtaba Khallash",
    "Mossroy",
    "Mustafa Dagher",
    "Mustafa Ulu",
    "Nandan R Shenoy",
    "Nandha Reddy",
    "Nanmozhi AN",
    "Narve Sætre",
    "Nathanyel Sandi",
    "Nazli Kaya",
    "Nedyalko Nikolov",
    "nesies",
    "NFehringVHV",
    "Nibin Geevarghese",
    "Nick Papirniy",
    "Nico Korthout",
    "Nico Rehwaldt",
    "Nico Rutishauser",
    "Nico Van Belle",
    "Nicola Puppa",
    "Nicolas Pepin-Perreault",
    "Niklas Mollenhauer",
    "Nikola Koevski",
    "ninckblokje",
    "Nithin S. Sabu",
    "Norman",
    "nov rain",
    "nygmaaa",
    "Németh Tamás",
    "Oleksandr Kriuchenko",
    "Oleksandr Maksiuta",
    "Oleksii Ivanov",
    "OleksiiIvanov",
    "Oliver Steinhauer",
    "Omran Abazid",
    "Oğuz Eroğlu",
    "p3trur0",
    "Panagiotis Goutis",
    "Patrick Dehn",
    "Patrick Pötz",
    "Patrick Wunderlich",
    "Paul K Deuster",
    "Paul Pogonyshev",
    "Pavel Kotelevskii",
    "Pavel Pletnev",
    "Peter Ihme",
    "Petr Škácha",
    "Philip Stahl",
    "Philipp Fromme",
    "Philipp Kief",
    "Philipp Ossler",
    "Philipp Schaller",
    "piccinin-esteco",
    "Pierre-Yves",
    "Piyush",
    "prajwol bhandari",
    "Prakash Palanisamy",
    "Pranjal Goyal",
    "Prithviraj",
    "psavidis",
    "punitdarira",
    "Radek Postołowicz",
    "Rafael Cordones",
    "Ragnar Nevries",
    "Ralf Puchert",
    "Ramūnas",
    "rasmusfaber",
    "Reddy Kishore Mannuru",
    "RedMser",
    "Rei",
    "Reiner Taglang",
    "Remco",
    "Ricardo Matias",
    "richardmward",
    "rnewton-bp3",
    "rob2universe",
    "Robert",
    "Robert Flores",
    "robert-sorkin",
    "Rodrigo Lopes",
    "rodrigolourencolopes",
    "rogertx",
    "Roland Weisleder",
    "Roman Smirnov",
    "Ronny Bräunlich",
    "sam",
    "Sara Lolatte",
    "Sayak Mukhopadhyay",
    "sccalabr",
    "Sebastian Bathke",
    "Sebastian Bittmann",
    "Sebastian Frick",
    "Sebastian Gülpen",
    "Sebastian Menski",
    "Sebastian Stamm",
    "Seif Ghezala",
    "Sergei Koshechkin",
    "SergejMeister",
    "sergiizakharov",
    "Sergio Rossi",
    "Shang-Hao Yang",
    "Shannon",
    "Shay",
    "sheldt",
    "Sherrin Raji",
    "Siddharth Mishra",
    "Sidharth",
    "Simon",
    "Simon Sobisch",
    "Simon Sprünker",
    "Simon Zambrovski",
    "Simon Zengerling",
    "skayliu",
    "snehalbiju12",
    "Sorin Ardelean",
    "Soumik",
    "Sourav Jha",
    "Sowmya H L",
    "stannnous",
    "Stefan Jacobi",
    "Stefan Ruijsenaars",
    "Stefan Schulze",
    "Stefan Zilske",
    "Stephan E.",
    "stephanpelikan",
    "Stephen Russett",
    "Steven Harrison",
    "Steven Hicks",
    "Stijn Vlaes",
    "strangelookingnerd",
    "sumankumarpani",
    "Sumindar",
    "Summit58 LLC",
    "Suraj Menon",
    "Svetlana Dorokhova",
    "Szabó Péter",
    "tahaarian",
    "Tassilo Weidner-Mühl",
    "TheSharpieOne Bot",
    "Thomas Allan",
    "Thomas Lefèvre",
    "Thomas Skjølberg",
    "thomasbeyerberlin",
    "Thorben Lindhauer",
    "Tiese Barrell",
    "Tilen Faganel",
    "till-stadtler",
    "Tim Kräuter",
    "Timo Kramer",
    "Timon Lazar",
    "Timothy Cline",
    "Tobias Conz",
    "Tobias Metzke-Bernstein",
    "Tobias Schaefer",
    "Tobias Trame",
    "Tom Baeyens",
    "Tom Crossland",
    "Torge Hamann",
    "tsfans",
    "Ubaldo Pescatore",
    "Ulaş Akdeniz",
    "Valentin Serra",
    "Valentin Vago",
    "Vibhuti1402agg",
    "Victor Mosin",
    "Victor Naumov",
    "vicvolk",
    "Ville Heinila",
    "Vincent Boulet",
    "Vincent Fuchs",
    "Vincent Thiery",
    "Vinícius Goulart",
    "Vishal Kumar Singh",
    "vjachyslav",
    "Vlad Tkachenko",
    "Vladimir Katushenok",
    "Vladislav Karamfilov",
    "vojimir golem",
    "Volker Buzek",
    "Volodymyr Melnyk",
    "Vuk Vasić",
    "Vítor Tavares",
    "WaiKit",
    "winwin2011",
    "Wojciech Grajewski",
    "Wolf Sluyterman van Langeweyde",
    "Xiangkun Yin",
    "yachtintheband",
    "yanavasileva",
    "Yash Pardeshi",
    "Yedidiah Tsedeke",
    "Yevhen Podluzhnyi",
    "Yohan Fernando",
    "Yuliia Saienko",
    "YuliiaKorsun",
    "yyko",
    "Zhang Chao",
    "zHd4",
    "zlh",
    "Zoltan Kalmar",
    "李 銍"
  ],
  "counts": {
    "total": 510,
    "engine": 411,
    "modeling": 135
  }
} as const;
