#!/usr/bin/env python3
"""Generate stub trait implementations for the generated REST layer.

The rust-axum router (`camunda_gateway_rest::server::new`) requires a single type
that implements every per-tag API trait. Writing those impls by hand (hundreds of
methods) is infeasible and would rot whenever the spec changes, so this script
derives them from the generated trait definitions in
`generated/src/apis/*.rs`.

Every generated method body is `Err(())`, which routes through the server type's
`ErrorHandler` implementation. The hand-written server (server/src/main.rs) maps
that to `501 Not Implemented`, giving a fully routable stub server with no backend
wiring.

Usage:
    gen-stub-server.py <generated-apis-dir> <output-rs-file>
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

TRAIT_RE = re.compile(r"pub trait (?P<name>\w+)<E\b")
HAS_CLAIMS_RE = re.compile(r"^\s*type Claims;", re.MULTILINE)
METHOD_RE = re.compile(
    r"async fn (?P<name>\w+)\((?P<params>[\s\S]*?)\)\s*->\s*Result<\s*(?P<resp>\w+)\s*,\s*E\s*>;"
)

# (module, method) -> body expression that delegates to a hand-written method on
# `ServerImpl` (defined in server/src/main.rs) instead of returning `Err(())`.
# This is how specific operations get wired to the embedded nanobpmn engine while
# every other operation stays a 501 stub. The signatures are still generated, so
# they never drift from the spec.
OVERRIDES: dict[tuple[str, str], str] = {
    ("process_instance", "create_process_instance"): "self.create_process_instance_impl(body).await",
    ("job", "complete_job"): "self.complete_job_impl(path_params, body).await",
    ("resource", "create_deployment"): "self.create_deployment_impl(body).await",
    ("job", "activate_jobs"): "self.activate_jobs_impl(body).await",
    ("job", "fail_job"): "self.fail_job_impl(path_params, body).await",
    ("job", "throw_job_error"): "self.throw_job_error_impl(path_params, body).await",
    ("job", "update_job"): "self.update_job_impl(path_params, body).await",
    ("incident", "resolve_incident"): "self.resolve_incident_impl(path_params, body).await",
    ("incident", "get_incident"): "self.get_incident_impl(path_params).await",
    ("incident", "search_incidents"): "self.search_incidents_impl(body).await",
    ("process_instance", "get_process_instance"): "self.get_process_instance_impl(path_params).await",
    ("element_instance", "create_element_instance_variables"): "self.create_element_instance_variables_impl(path_params, body).await",
}

HEADER = """// @generated by gateway-rust/scripts/gen-stub-server.py - DO NOT EDIT.
//
// Stub implementations of every generated API trait for `crate::ServerImpl`.
// Each method returns `Err(())`, which the server's ErrorHandler maps to a
// 501 Not Implemented response, EXCEPT for the operations listed in OVERRIDES
// (wired to the embedded nanobpmn engine). Regenerate with `make generate`.
#![allow(unused_variables, unused_imports, clippy::all)]

use async_trait::async_trait;
use axum::extract::*;
use axum_extra::extract::CookieJar;
use bytes::Bytes;
use camunda_gateway_rest::{apis, models, types::*};
use headers::Host;
use http::Method;

use crate::ServerImpl;
"""


def render_trait_impl(module: str, source: str) -> str | None:
    trait_match = TRAIT_RE.search(source)
    if not trait_match:
        return None
    trait = trait_match.group("name")
    has_claims = bool(HAS_CLAIMS_RE.search(source))

    methods: list[str] = []
    for m in METHOD_RE.finditer(source):
        name = m.group("name")
        params = m.group("params").rstrip()
        resp = m.group("resp")
        body = OVERRIDES.get((module, name), "Err(())")
        methods.append(
            f"    async fn {name}({params}\n"
            f"    ) -> Result<apis::{module}::{resp}, ()> {{\n"
            f"        {body}\n"
            f"    }}\n"
        )

    if not methods:
        return None

    body = "\n".join(methods)
    claims = "    type Claims = ();\n\n" if has_claims else ""
    return (
        f"#[async_trait]\n"
        f"impl apis::{module}::{trait}<()> for ServerImpl {{\n"
        f"{claims}{body}}}\n"
    )


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(f"usage: {argv[0]} <generated-apis-dir> <output-rs-file>", file=sys.stderr)
        return 2

    apis_dir = Path(argv[1]).resolve()
    output = Path(argv[2]).resolve()
    if not apis_dir.is_dir():
        print(f"generated apis dir not found: {apis_dir}", file=sys.stderr)
        return 1

    impls: list[str] = []
    trait_count = 0
    for src in sorted(apis_dir.glob("*.rs")):
        if src.stem == "mod":
            continue
        rendered = render_trait_impl(src.stem, src.read_text(encoding="utf-8"))
        if rendered is not None:
            impls.append(rendered)
            trait_count += 1

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(HEADER + "\n" + "\n".join(impls), encoding="utf-8")
    print(f"Generated stub impls for {trait_count} API traits -> {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
