#!/usr/bin/env python3
"""Generate the spec-derived response-contract bundle for the REST gateway.

For every operation in the (sanitized) OpenAPI spec this emits, per documented
HTTP status code, a self-contained JSON-Schema for the response body. The
gateway's outbound response-contract guard (server/src/response_contract.rs)
loads the bundle and validates the serialized response of every *implemented*
operation against the schema for its actual status code — turning silent
contract drift (e.g. a JOB wait state missing the required `jobType`) into an
immediate, attributable 500 at the source. See Magikcraft/nano-bpm#1011 / #1010.

Derivation over duplication: the schemas are derived from the SAME spec tree
that generates the server (`spec/` -> sanitized `build/spec/` -> `generated/`),
never hand-maintained. The set of *implemented* operations is imported directly
from gen-stub-server.py's OVERRIDES map (its single source of truth), so the two
never drift.

Output is a single JSON document (git-ignored, regenerated by `make generate`):

    {
      "defs":       { "<DefName>": <json-schema>, ... },   // shared $defs pool
      "operations": [
        { "operationId": "...", "method": "POST", "path": "/v2/...",
          "implemented": true,
          "responses": { "200": <json-schema>, "400": <json-schema>, ... } },
        ...
      ]
    }

Each response schema (and every entry in `defs`) is an OpenAPI-3.0 schema
translated to a JSON-Schema the runtime validator understands: cross-file/local
`$ref`s are rewritten to `#/defs/<DefName>`, and OpenAPI `nullable: true` is
translated to an explicit `null` alternative (`anyOf: [ {type: null}, ... ]`).

Usage:
    gen-response-contract.py <sanitized-spec-dir> <spec-entrypoint> <output-json>
"""
from __future__ import annotations

import importlib.util
import json
import re
import sys
from pathlib import Path
from typing import Any

import yaml

HTTP_METHODS = ("get", "put", "post", "delete", "patch", "options", "head", "trace")
# Body media types we validate. Everything else (binary, xml, text) is skipped.
JSON_MEDIA_TYPES = ("application/json", "application/problem+json")
# OpenAPI/JSON-Schema keywords the runtime validator understands and we preserve.
# Everything else (description, example, discriminator, readOnly, min/max, …) is
# dropped: it is either documentation or a constraint we deliberately do not
# enforce at the wire (to avoid false-positive 500s on the hot path).
KEPT_KEYWORDS = (
    "type",
    "enum",
    "const",
    "properties",
    "required",
    "items",
    "additionalProperties",
    "allOf",
    "oneOf",
    "anyOf",
    "format",
)


def _load_overrides(script_dir: Path) -> set[str]:
    """Import gen-stub-server.py and return the set of implemented (wired)
    generated method names — the single source of truth for which operations
    return a real `Ok(Resp)` (and so must be validated) vs a 501 stub."""
    src = script_dir / "gen-stub-server.py"
    spec = importlib.util.spec_from_file_location("gen_stub_server", src)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot import {src}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return {method for (_module, method) in module.OVERRIDES}


_CAMEL_BOUNDARY = re.compile(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])")


def _snake(operation_id: str) -> str:
    """camelCase operationId -> snake_case generated method name (mirrors the
    rust-axum generator's naming), so we can test membership in OVERRIDES."""
    return _CAMEL_BOUNDARY.sub("_", operation_id).lower()


class SpecResolver:
    """Loads spec YAML files on demand and resolves $refs (local `#/…` and
    cross-file `other.yaml#/…`) relative to the file the $ref appears in."""

    def __init__(self, spec_dir: Path) -> None:
        self.spec_dir = spec_dir
        self._docs: dict[Path, Any] = {}

    def load(self, path: Path) -> Any:
        path = path.resolve()
        if path not in self._docs:
            with path.open("r", encoding="utf-8") as fh:
                self._docs[path] = yaml.safe_load(fh)
        return self._docs[path]

    def resolve(self, ref: str, base_file: Path) -> tuple[Any, Path]:
        file_part, _, pointer = ref.partition("#")
        target_file = base_file if file_part == "" else (base_file.parent / file_part)
        target_file = target_file.resolve()
        node = self._navigate(self.load(target_file), pointer)
        return node, target_file

    @staticmethod
    def _navigate(doc: Any, pointer: str) -> Any:
        node = doc
        for raw in pointer.split("/"):
            if raw == "":
                continue
            token = raw.replace("~1", "/").replace("~0", "~")
            if isinstance(node, list):
                node = node[int(token)]
            else:
                node = node[token]
        return node


class ContractBuilder:
    def __init__(self, resolver: SpecResolver) -> None:
        self.resolver = resolver
        # (target_file, pointer) -> def name (stable, deduplicated).
        self._def_keys: dict[tuple[Path, str], str] = {}
        self._used_names: set[str] = set()
        self.defs: dict[str, Any] = {}

    # -- $ref registration -------------------------------------------------
    def _register_ref(self, ref: str, base_file: Path) -> str:
        node, target_file = self.resolver.resolve(ref, base_file)
        _, _, pointer = ref.partition("#")
        key = (target_file, pointer)
        if key in self._def_keys:
            return self._def_keys[key]
        name = self._alloc_name(pointer, target_file)
        self._def_keys[key] = name
        # Reserve the slot before converting so a recursive schema that refers
        # back to itself resolves to the same def instead of looping forever.
        self.defs[name] = None
        self.defs[name] = self.convert(node, target_file)
        return name

    def _alloc_name(self, pointer: str, target_file: Path) -> str:
        base = pointer.rstrip("/").split("/")[-1] or target_file.stem
        base = re.sub(r"[^0-9A-Za-z_]", "_", base)
        name = base
        i = 2
        while name in self._used_names:
            name = f"{base}_{i}"
            i += 1
        self._used_names.add(name)
        return name

    # -- schema translation ------------------------------------------------
    def convert(self, node: Any, base_file: Path) -> Any:
        if not isinstance(node, dict):
            # Booleans (`additionalProperties: true`) and other scalars pass
            # through unchanged.
            return node

        if "$ref" in node:
            name = self._register_ref(node["$ref"], base_file)
            return {"$ref": f"#/defs/{name}"}

        nullable = node.get("nullable") is True
        out: dict[str, Any] = {}
        for key in KEPT_KEYWORDS:
            if key not in node:
                continue
            value = node[key]
            if key == "properties" and isinstance(value, dict):
                out[key] = {
                    prop: self.convert(sub, base_file) for prop, sub in value.items()
                }
            elif key in ("allOf", "oneOf", "anyOf") and isinstance(value, list):
                out[key] = [self.convert(sub, base_file) for sub in value]
            elif key == "items":
                out[key] = self.convert(value, base_file)
            elif key == "additionalProperties" and isinstance(value, dict):
                out[key] = self.convert(value, base_file)
            else:
                out[key] = value

        if nullable:
            # OpenAPI 3.0 `nullable: true` -> an explicit null alternative that
            # a plain JSON-Schema validator understands.
            return {"anyOf": [{"type": "null"}, out]}
        return out

    # -- operations --------------------------------------------------------
    def response_schema(self, response_obj: Any, base_file: Path) -> Any | None:
        """Extract and translate the JSON body schema from a response object,
        following a top-level `$ref` to a shared response component first."""
        node, cur_file = response_obj, base_file
        if isinstance(node, dict) and "$ref" in node:
            node, cur_file = self.resolver.resolve(node["$ref"], base_file)
        if not isinstance(node, dict):
            return None
        content = node.get("content")
        if not isinstance(content, dict):
            return None
        for media_type in JSON_MEDIA_TYPES:
            media = content.get(media_type)
            if isinstance(media, dict) and isinstance(media.get("schema"), dict):
                return self.convert(media["schema"], cur_file)
        return None


def _normalize_path(path: str) -> str:
    """`/v2/element-instances/{elementInstanceKey}` -> `/v2/element-instances/{}`
    so route lookup is independent of the (differently-cased) parameter names the
    axum router uses. Path structure + method uniquely identify an operation."""
    return re.sub(r"\{[^}]*\}", "{}", path)


def build(spec_dir: Path, entrypoint: str, overrides: set[str]) -> dict[str, Any]:
    resolver = SpecResolver(spec_dir)
    builder = ContractBuilder(resolver)

    operations: list[dict[str, Any]] = []
    seen_ops: set[str] = set()

    # Every spec file may carry a `paths` block (the spec is split per tag).
    for src in sorted(spec_dir.rglob("*.yaml")) + sorted(spec_dir.rglob("*.yml")):
        doc = resolver.load(src)
        if not isinstance(doc, dict):
            continue
        paths = doc.get("paths")
        if not isinstance(paths, dict):
            continue
        for raw_path, path_item in paths.items():
            if not isinstance(path_item, dict):
                continue
            for method in HTTP_METHODS:
                op = path_item.get(method)
                if not isinstance(op, dict):
                    continue
                operation_id = op.get("operationId")
                if not isinstance(operation_id, str) or operation_id in seen_ops:
                    continue
                seen_ops.add(operation_id)
                responses = op.get("responses")
                if not isinstance(responses, dict):
                    continue
                schemas: dict[str, Any] = {}
                for status, response_obj in responses.items():
                    status_str = str(status)
                    if not status_str.isdigit():
                        continue  # skip "default" / ranges
                    schema = builder.response_schema(response_obj, src)
                    if schema is not None:
                        schemas[status_str] = schema
                if not schemas:
                    continue
                operations.append(
                    {
                        "operationId": operation_id,
                        "method": method.upper(),
                        "path": _normalize_path("/v2" + raw_path),
                        "implemented": _snake(operation_id) in overrides,
                        "responses": schemas,
                    }
                )

    operations.sort(key=lambda o: o["operationId"])
    return {"defs": builder.defs, "operations": operations}


def main(argv: list[str]) -> int:
    if len(argv) != 4:
        print(
            f"usage: {argv[0]} <sanitized-spec-dir> <spec-entrypoint> <output-json>",
            file=sys.stderr,
        )
        return 2

    spec_dir = Path(argv[1]).resolve()
    entrypoint = argv[2]
    output = Path(argv[3]).resolve()
    if not spec_dir.is_dir():
        print(f"sanitized spec dir not found: {spec_dir}", file=sys.stderr)
        return 1

    script_dir = Path(argv[0]).resolve().parent
    overrides = _load_overrides(script_dir)

    bundle = build(spec_dir, entrypoint, overrides)

    output.parent.mkdir(parents=True, exist_ok=True)
    # Stable, sorted keys so regeneration is byte-deterministic (a clean diff /
    # freshness gate).
    output.write_text(
        json.dumps(bundle, indent=1, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    implemented = sum(1 for o in bundle["operations"] if o["implemented"])
    print(
        f"Generated response contract: {len(bundle['operations'])} operations "
        f"({implemented} implemented), {len(bundle['defs'])} schemas -> {output}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
